-- Migration: Reset properties and insert 5 sample properties
-- Purpose: Clear all property data and replace with 5 clean samples showing all field titles

-- Step 1: Delete all dependent data first (children before parent)
DELETE FROM public.property_contacts;
DELETE FROM public.client_property_matches;
DELETE FROM public.viewings;
DELETE FROM public.enquiries WHERE property_id IS NOT NULL;
DELETE FROM public.properties;

-- Step 2: Insert 5 sample properties covering all key fields
DO $$
DECLARE
    prop1_id UUID := gen_random_uuid();
    prop2_id UUID := gen_random_uuid();
    prop3_id UUID := gen_random_uuid();
    prop4_id UUID := gen_random_uuid();
    prop5_id UUID := gen_random_uuid();
BEGIN

    -- Sample 1: Woodgreen Court - 2BR for rent, leased
    INSERT INTO public.properties (
        id,
        property_ref,
        short_code,
        building_name,
        village,
        phase,
        block,
        floor,
        unit,
        address,
        prop_types,
        prop_type,
        bedrooms,
        bathrooms,
        saleable_area,
        gross_area,
        asking_rent,
        asking_price,
        status,
        occupancy,
        contact_status,
        landlord_name,
        landlord_phone,
        landlord_email,
        tenant_name,
        tenant_phone,
        lease_start,
        lease_end,
        management_fee,
        notes,
        validation_status
    ) VALUES (
        prop1_id,
        'WGC-001',
        'WGC0011C',
        'Woodgreen Court',
        'Discovery Bay',
        'Phase 3',
        'Block A',
        '11',
        '11C',
        'Flat 11C, Woodgreen Court, Discovery Bay',
        'Apartment',
        'Apartment',
        2,
        2,
        850,
        1100,
        22000,
        NULL,
        'for-rent',
        'leased',
        'active',
        'James Wong',
        '+852 9123 4567',
        'james.wong@email.com',
        'Sarah Mitchell',
        '+852 6234 5678',
        '2024-01-01',
        '2025-12-31',
        5,
        'Corner unit with sea view. Recently renovated kitchen.',
        'valid'
    )
    ON CONFLICT (property_ref) DO NOTHING;

    -- Sample 2: Seabee Lane - 3BR for sale and rent, vacant
    INSERT INTO public.properties (
        id,
        property_ref,
        short_code,
        building_name,
        village,
        phase,
        block,
        floor,
        unit,
        address,
        prop_types,
        prop_type,
        bedrooms,
        bathrooms,
        saleable_area,
        gross_area,
        asking_rent,
        asking_price,
        status,
        occupancy,
        contact_status,
        landlord_name,
        landlord_phone,
        landlord_email,
        tenant_name,
        tenant_phone,
        lease_start,
        lease_end,
        management_fee,
        notes,
        validation_status
    ) VALUES (
        prop2_id,
        'SBL-002',
        'SBL0053A',
        'Seabee Lane',
        'Discovery Bay',
        'Phase 1',
        'Block B',
        '5',
        '5A',
        'Flat 5A, Seabee Lane, Discovery Bay',
        'House',
        'House',
        3,
        2,
        1200,
        1450,
        35000,
        6800000,
        'for-sale-and-rent',
        'vacant',
        'active',
        'Linda Chan',
        '+852 9876 5432',
        'linda.chan@email.com',
        NULL,
        NULL,
        NULL,
        NULL,
        5,
        'Large garden terrace. Available immediately.',
        'valid'
    )
    ON CONFLICT (property_ref) DO NOTHING;

    -- Sample 3: Twilight Court - 1BR for rent, vacant soon
    INSERT INTO public.properties (
        id,
        property_ref,
        short_code,
        building_name,
        village,
        phase,
        block,
        floor,
        unit,
        address,
        prop_types,
        prop_type,
        bedrooms,
        bathrooms,
        saleable_area,
        gross_area,
        asking_rent,
        asking_price,
        status,
        occupancy,
        contact_status,
        landlord_name,
        landlord_phone,
        landlord_email,
        tenant_name,
        tenant_phone,
        lease_start,
        lease_end,
        management_fee,
        notes,
        validation_status
    ) VALUES (
        prop3_id,
        'TWI-003',
        'TWI0082B',
        'Twilight Court',
        'Discovery Bay',
        'Phase 2',
        'Tower C',
        '8',
        '8B',
        'Flat 8B, Twilight Court, Discovery Bay',
        'Studio',
        'Studio',
        1,
        1,
        450,
        580,
        14000,
        NULL,
        'for-rent',
        'vacant-soon',
        'active',
        'Michael Lee',
        '+852 5567 8901',
        'michael.lee@email.com',
        'Tom Nakamura',
        '+852 6789 0123',
        '2023-06-01',
        '2025-05-31',
        5,
        'High floor with mountain view. Tenant vacating end of May.',
        'valid'
    )
    ON CONFLICT (property_ref) DO NOTHING;

    -- Sample 4: Bayside Villa - 4BR for sale, self-occupy
    INSERT INTO public.properties (
        id,
        property_ref,
        short_code,
        building_name,
        village,
        phase,
        block,
        floor,
        unit,
        address,
        prop_types,
        prop_type,
        bedrooms,
        bathrooms,
        saleable_area,
        gross_area,
        asking_rent,
        asking_price,
        status,
        occupancy,
        contact_status,
        landlord_name,
        landlord_phone,
        landlord_email,
        tenant_name,
        tenant_phone,
        lease_start,
        lease_end,
        management_fee,
        notes,
        validation_status
    ) VALUES (
        prop4_id,
        'BSV-004',
        'BSV0011A',
        'Bayside Villa',
        'Discovery Bay',
        'Phase 5',
        'Block D',
        '1',
        '1A',
        'Villa 1A, Bayside Villa, Discovery Bay',
        'Villa',
        'Villa',
        4,
        3,
        2100,
        2600,
        NULL,
        12500000,
        'for-sale',
        'leased',
        'active',
        'Robert Cheung',
        '+852 9001 2345',
        'robert.cheung@email.com',
        'Emily Davis',
        '+852 6345 6789',
        '2024-03-01',
        '2026-02-28',
        5,
        'Duplex villa with private pool and roof terrace. Owner selling.',
        'valid'
    )
    ON CONFLICT (property_ref) DO NOTHING;

    -- Sample 5: Harbour Peak - 2BR for rent, with TA
    INSERT INTO public.properties (
        id,
        property_ref,
        short_code,
        building_name,
        village,
        phase,
        block,
        floor,
        unit,
        address,
        prop_types,
        prop_type,
        bedrooms,
        bathrooms,
        saleable_area,
        gross_area,
        asking_rent,
        asking_price,
        status,
        occupancy,
        contact_status,
        landlord_name,
        landlord_phone,
        landlord_email,
        tenant_name,
        tenant_phone,
        lease_start,
        lease_end,
        management_fee,
        notes,
        validation_status
    ) VALUES (
        prop5_id,
        'HPK-005',
        'HPK0153C',
        'Harbour Peak',
        'Discovery Bay',
        'Phase 4',
        'Tower E',
        '15',
        '15C',
        'Flat 15C, Harbour Peak, Discovery Bay',
        'Apartment',
        'Apartment',
        2,
        1,
        720,
        900,
        18500,
        NULL,
        'for-rent',
        'with-ta',
        'active',
        'Grace Lam',
        '+852 9456 7890',
        'grace.lam@email.com',
        'David Thompson',
        '+852 6890 1234',
        '2025-02-01',
        '2027-01-31',
        5,
        'High floor harbour view. Tenancy agreement signed, pending move-in.',
        'valid'
    )
    ON CONFLICT (property_ref) DO NOTHING;

    -- Insert sample contacts for each property
    INSERT INTO public.property_contacts (
        id, property_ref, short_code, contact_role, contact_person, contact_number, contact_email, notes
    ) VALUES
        (gen_random_uuid(), 'WGC-001', 'WGC0011C', 'owner',    'James Wong',    '+852 9123 4567', 'james.wong@email.com',    'Primary landlord contact'),
        (gen_random_uuid(), 'WGC-001', 'WGC0011C', 'tenant',   'Sarah Mitchell','+852 6234 5678', 'sarah.mitchell@email.com','Current tenant'),
        (gen_random_uuid(), 'SBL-002', 'SBL0053A', 'owner',    'Linda Chan',    '+852 9876 5432', 'linda.chan@email.com',    'Owner - selling or renting'),
        (gen_random_uuid(), 'TWI-003', 'TWI0082B', 'owner',    'Michael Lee',   '+852 5567 8901', 'michael.lee@email.com',   'Landlord'),
        (gen_random_uuid(), 'TWI-003', 'TWI0082B', 'tenant',   'Tom Nakamura',  '+852 6789 0123', 'tom.nakamura@email.com',  'Vacating end of May 2025'),
        (gen_random_uuid(), 'BSV-004', 'BSV0011A', 'owner',    'Robert Cheung', '+852 9001 2345', 'robert.cheung@email.com', 'Owner selling'),
        (gen_random_uuid(), 'BSV-004', 'BSV0011A', 'tenant',   'Emily Davis',   '+852 6345 6789', 'emily.davis@email.com',   'Current tenant'),
        (gen_random_uuid(), 'HPK-005', 'HPK0153C', 'owner',    'Grace Lam',     '+852 9456 7890', 'grace.lam@email.com',     'Landlord'),
        (gen_random_uuid(), 'HPK-005', 'HPK0153C', 'tenant',   'David Thompson','+852 6890 1234', 'david.thompson@email.com','TA signed - pending move-in')
    ON CONFLICT (id) DO NOTHING;

    RAISE NOTICE 'Sample data inserted: 5 properties with contacts';

EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Sample data insertion failed: %', SQLERRM;
END $$;
